version: "3.8"

services:
  frontend:
    image: dipesh2009/scribble_hub-frontend:${IMAGE_TAG:-latest}
    container_name: scribble-frontend
    ports:
      - "3003:3003"
    build:
      context: .
      dockerfile: ./docker/Dockerfile.frontend
      args:
        - DATABASE_URL=${DATABASE_URL:-postgresql://postgres:postgres@localhost:5432/postgres}
        - BACKEND_URL=${BACKEND_URL:-http://http-backend:3000}
        - WS_URL=${WS_URL:-ws://ws-backend:3002}
        - SCRIBBLE_FRONTEND_URL=${FRONTEND_URL:-http://localhost:3003}
    depends_on:
      - http-backend
      - ws-backend

  http-backend:
    image: dipesh2009/scribble_hub-backend:${IMAGE_TAG:-latest}
    container_name: http-backend
    ports:
      - "3000:3000"
    build:
      context: .
      dockerfile: ./docker/Dockerfile.backend
      args:
        - DATABASE_URL=${DATABASE_URL:-postgresql://postgres:postgres@localhost:5432/postgres}
        - FRONTEND_URL=${FRONTEND_URL:-http://localhost:3003}

  ws-backend:
    image: dipesh2009/scribble_hub-websocket:${IMAGE_TAG:-latest}
    container_name: ws-backend
    ports:
      - "3002:3002"
    build:
      context: .
      dockerfile: ./docker/Dockerfile.websocket
      args:
        - DATABASE_URL=${DATABASE_URL:-postgresql://postgres:postgres@localhost:5432/postgres}
