FROM node:20-alpine
WORKDIR /user/src/app

COPY ./packages ./packages
COPY ./package.json ./package.json

COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./pnpm-workspace.yaml ./pnpm-workspace.yaml
COPY ./turbo.json ./turbo.json
COPY ./apps/ws-backend ./apps/ws-backend

RUN npm install -g pnpm
RUN pnpm install
RUN pnpm run db:generate

RUN npm run build

# EXPOSE 3000
CMD ["npm", "run", "start:ws"]
