FROM node:20-alpine

WORKDIR /user/src/app

ARG DATABASE_URL
ARG NEXT_PUBLIC_LLM_URL
ARG NEXT_PUBLIC_LLM_TOKEN

ENV DATABASE_URL=${DATABASE_URL}
ENV NEXT_PUBLIC_LLM_URL=${NEXT_PUBLIC_LLM_URL}
ENV NEXT_PUBLIC_LLM_TOKEN=${NEXT_PUBLIC_LLM_TOKEN}

ARG BACKEND_URL
ENV BACKEND_URL=${BACKEND_URL}
ENV NEXT_PUBLIC_BACKEND_URL=${BACKEND_URL}

ARG WS_URL
ENV WS_URL=${WS_URL}
ENV NEXT_PUBLIC_WS_URL=${WS_URL}

ARG FRONTEND_URL
ENV FRONTEND_URL=${FRONTEND_URL}
ENV NEXT_PUBLIC_FRONTEND_URL=${FRONTEND_URL}

COPY ./packages ./packages
COPY ./package.json ./package.json

COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./pnpm-workspace.yaml ./pnpm-workspace.yaml
COPY ./turbo.json ./turbo.json
COPY ./apps/scribbledraw-frontend ./apps/scribbledraw-frontend

RUN npm install -g pnpm
RUN pnpm install
RUN cd ./packages/db && npx prisma generate && cd ../..

RUN npm run build

EXPOSE 3003
CMD ["npm", "run", "start:web"]
