FROM node:20-alpine

WORKDIR /user/src/app

ARG DATABASE_URL
ARG NEXT_PUBLIC_LLM_URL
ARG NEXT_PUBLIC_LLM_TOKEN

ENV DATABASE_URL=${DATABASE_URL}
ENV NEXT_PUBLIC_LLM_URL=${NEXT_PUBLIC_LLM_URL}
ENV NEXT_PUBLIC_LLM_TOKEN=${NEXT_PUBLIC_LLM_TOKEN}

COPY ./packages ./packages
COPY ./package.json ./package.json

COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./pnpm-workspace.yaml ./pnpm-workspace.yaml
COPY ./turbo.json ./turbo.json
COPY ./apps/scribbledraw-frontend ./apps/scribbledraw-frontend

RUN npm install -g pnpm
RUN pnpm install
RUN cd ./packages/db && npx prisma generate && cd ../..

RUN npm run build

# EXPOSE 3000
CMD ["npm", "run", "start:web"]
